<div class="box">
    <h3>Manual</h3>
    <ul id="bonsai">
        <li><a href="index.php?location=manual&section=main">Main</a></li>
        <li>
            <a href="index.php?location=manual&section=baseclasses">Base Classes</a>
            <ul>
                <li><a href="index.php?location=manual&section=baseclasses&page=113">Anti-Paladin</a></li>
                <li><a href="index.php?location=manual&section=baseclasses&page=125">Archer</a></li>
                <li><a href="index.php?location=manual&section=baseclasses&page=0">Barbarian</a></li>
                <li><a href="index.php?location=manual&section=baseclasses&page=1">Bard</a></li>
            </ul>
        </li>
        <li><a href="index.php?location=manual&section=prestigeclasses">Prestige Classes</a></li>
        <li><a href="index.php?location=manual&section=domains">Domains</a></li>
        <li><a href="index.php?location=manual&section=feats">Feats</a></li>
        <li><a href="index.php?location=manual&section=epicfeats">Epic Feats</a></li>
        <li><a href="index.php?location=manual&section=psionicpowers">Psionic Powers</a></li>
        <li><a href="index.php?location=manual&section=utterances">Truename Utterances</a></li>
        <li><a href="index.php?location=manual&section=races">Races</a></li>
        <li><a href="index.php?location=manual&section=skills">Skills</a></li>
        <li><a href="index.php?location=manual&section=spells">Spells</a></li>
        <li><a href="index.php?location=manual&section=epicspells">Epic Spells</a></li>
        <li><a href="index.php?location=manual&section=modifiedspells">Modified Spells</a></li>

        <li><a href="index.php?location=manual&section=installation">Installation</a></li>
        <li><a href="index.php?location=manual&section=playersguide">Player's Guide</a></li>
        <li><a href="index.php?location=manual&section=modulebuilding">Module Building</a></li>
        <li><a href="index.php?location=manual&section=prcmaking">PrC Making</a></li>
    </ul>
</div>